Repository KUSITMS-30th-TEAM-A/frontend, pull requests merged in 2024-11, with the labels that each got.

#9 (#7) 🎨 design: 홈 화면 구현
  package-lock.json
  src/assets/svg/beginner_guide.svg
  src/assets/svg/chatbot_button.svg
  src/assets/webp/chatbot_button.webp
  src/components/button/ChatBot.tsx
  src/components/chips/BignnerGuide.tsx
  src/components/dialogs/BignnerGuideDialog.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/components/Dropdown.tsx
  src/pages/Main/components/JamsilSeat.tsx
  src/pages/Main/components/KtwizSeat.tsx
  src/pages/Main/components/SeatRecommendButton.tsx
  src/pages/Main/components/StadiumInfo.tsx
Labels: 🎨 design, 🚀 feat, 🐰 EUNHAK

#11 (#4) 🚀 feat: 온보딩 동작 로직 구현
  package-lock.json
  package.json
  src/pages/Main/Main.tsx
  src/pages/Onboarding/Login/InitPage.tsx
  src/pages/Onboarding/Login/LoginAuth.ts
  src/pages/Onboarding/Login/LoginPage.tsx
  src/pages/Onboarding/Onboarding.tsx
  src/pages/Onboarding/Signup/SignupPage.tsx
  src/pages/Onboarding/Signup/SignupPage1.tsx
  src/pages/Onboarding/Signup/SignupPage2.tsx
  src/pages/Onboarding/Signup/SignupPage3.tsx
  src/pages/Recommendation/Question.tsx
  src/pages/Recommendation/Question/Question1.tsx
  src/pages/_app.tsx
Labels: 🎨 design, 🚀 feat, 🐻 INAE

#13 (#8) 🎨 design: 구역 추천 질문 페이지 구현
  package-lock.json
  src/components/layout/Header.tsx
  src/components/layout/NavBar.tsx
  src/pages/Onboarding/Signup/SignupPage1.tsx
  src/pages/Onboarding/Signup/SignupPage2.tsx
  src/pages/Onboarding/Signup/SignupPage3.tsx
  src/pages/Recommendation/Question.tsx
  src/pages/Recommendation/Question/Question1.tsx
  src/pages/Recommendation/Question/Question2.tsx
  src/pages/Recommendation/Question/Question3.tsx
  src/pages/Recommendation/Question/Question4.tsx
  src/pages/Recommendation/components/HeaderBackBar.tsx
  src/pages/Recommendation/components/HeaderBar.tsx
Labels: 🎨 design, 🚀 feat, 🐻 INAE

#19 (#17) 🚀 feat: 로그인 API 구현
  package-lock.json
  package.json
  src/api/TestApiService.ts
  src/api/TestApiType.ts
  src/api/UserApiHandler.ts
  src/api/UserApiService.ts
  src/api/UserApiType.ts
  src/api/axiosInstance.ts
  src/pages/Main/Main.tsx
  src/pages/Onboarding/Login/LoginPage.tsx
  src/pages/Onboarding/Onboarding.tsx
  src/pages/Onboarding/Signup/SignupPage.tsx
  src/pages/_app.tsx
Labels: 🚀 feat, 🐻 INAE

#21 (#20) 🚀 feat: 챗봇, 추천 구역 가이드, 스타디움 api 구현
  src/api/ChatbotApiService.ts
  src/api/ChatbotApiType.ts
  src/api/ResultApiService.ts
  src/api/ResultApiType.ts
  src/api/StadiumApiService.ts
  src/api/StadiumApiType.ts
  src/api/UserApiService.ts
  src/api/UserApiType.ts
  src/api/axiosInstance.ts
  src/pages/Main/Main.tsx
Labels: 🚀 feat, 🐻 INAE

#27 (#22) 🚀 feat: 추천 질문, 추천 결과 API 구현
  package-lock.json
  src/api/ResultApiHandler.ts
  src/api/ResultApiService.ts
  src/api/StadiumApiService.ts
  src/api/StadiumApiType.ts
  src/constants/DummyData.ts
  src/constants/ZoneData.ts
  src/pages/Main/Main.tsx
  src/pages/Main/components/SeatRecommendButton.tsx
  src/pages/Recommend/Question.tsx
  src/pages/Recommend/Question/Question1.tsx
  src/pages/Recommend/Question/Question2.tsx
  src/pages/Recommend/Question/Question3.tsx
  src/pages/Recommend/Question/Question4.tsx
  src/pages/Recommend/Result.tsx
  src/pages/Recommendation/Result.tsx
  src/pages/_app.tsx
Labels: 🚀 feat, 🐻 INAE

#25 (#24) 🚀 feat: 구역 가이드 API 연동(수정 필요)
  src/api/StadiumApiHandler.ts
  src/api/StadiumApiService.ts
  src/api/StadiumApiType.ts
  src/components/dialogs/SeatTipDialog.tsx
  src/hooks/useModal.ts
  src/pages/Guide/Guide.tsx
  src/pages/Guide/components/GuideDetailContent.tsx
  src/pages/Recommend/Result.tsx
Labels: 🎨 design, 🚀 feat, 🐻 INAE

#35 (#32) 🎨 design: 메인 홈 디테일 수정
  package-lock.json
  package.json
  src/assets/svg/readyPopup.svg
  src/assets/svg/seat/jamsil_blue.svg
  src/assets/svg/seat/kt_cheer.svg
  src/assets/svg/seat/kt_kidsland.svg
  src/components/button/FloatingChatbotButton.tsx
  src/components/dialogs/ReadyStadiumDialog.tsx
  src/components/layout/HeaderCenter.tsx
  src/components/layout/MainHeader.tsx
  src/constants/ZoneData.ts
  src/pages/Guide/Guide.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/components/Dropdown.tsx
  src/pages/Main/components/JamsilSeat.tsx
  src/pages/Main/components/KtwizSeat.tsx
  src/pages/Main/components/SeatRecommendButton.tsx
  src/pages/_app.tsx
  src/styles/globals.css
  src/types/tailwind-scrollbar-hide.d.ts
Labels: 🎨 design, 🚀 feat, 🐰 EUNHAK

#37 (#34) 🚀 feat: 구역 가이드 API 업데이트 및 리다이렉트 구현
  src/api/StadiumApiHandler.ts
  src/api/StadiumApiType.ts
  src/components/dialogs/SeatTipDialog.tsx
  src/components/layout/NavBar.tsx
  src/hooks/useStadiumSelector.ts
  src/pages/Guide/Guide.tsx
  src/pages/Guide/components/GuideDetailContent.tsx
  src/pages/Guide/components/SeatDropdown.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/components/StadiumInfo.tsx
  src/pages/_app.tsx
Labels: 🎨 design, 🚀 feat, 🐻 INAE

#39 (#36) design: 챗봇 컴포넌트 수정
  src/assets/svg/chatbot_click.svg
  src/assets/svg/chatbot_lookie.svg
  src/components/layout/BackLogoBar.tsx
  src/pages/Chatbot/Chatbot.tsx
  src/pages/Chatbot/components/ChatInput.tsx
  src/pages/Chatbot/components/ChatbotStart.tsx
  src/pages/Chatbot/components/OptionsList.tsx
  src/pages/Chatbot/components/StadiumSelection.tsx
  src/pages/Guide/Guide.tsx
  src/pages/Guide/components/GuideDetailContent.tsx
  src/pages/Guide/components/SeatDropdown.tsx
  src/pages/Recommend/Question/Question1.tsx
  src/pages/Recommend/Question/Question2.tsx
  src/pages/Recommend/Question/Question3.tsx
  src/pages/Recommend/Question/Question4.tsx
Labels: 🎨 design, 🐰 EUNHAK

#42 (#41) 🎨 design: 구역 추천 페이지 세부 디자인 및 기능 수정
  src/components/layout/BackBar.tsx
  src/components/layout/BackLogoBar.tsx
  src/components/layout/HeaderBackBar.tsx
  src/components/layout/HeaderBar.tsx
  src/components/layout/HeaderCenter.tsx
  src/components/layout/MainHeader.tsx
  src/components/layout/ResultHeader.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/components/SeatRecommendButton.tsx
  src/pages/Recommend/Question.tsx
  src/pages/Recommend/Question/Question1.tsx
  src/pages/Recommend/Question/Question3.tsx
  src/pages/Recommend/Question/Question4.tsx
  src/pages/Recommend/Result.tsx
  src/pages/_app.tsx
Labels: 🎨 design, 🚀 feat, 🐻 INAE

#46 (#45) 🎨 design: 이미지 퀄리티 수정
  package-lock.json
  src/assets/svg/chatbot_floating_button.svg
  src/assets/svg/chatbot_lookie.svg
  src/assets/webp/seat/jamsil_blue.webp
  src/assets/webp/seat/jamsil_default.webp
  src/assets/webp/seat/jamsil_exciting.webp
  src/assets/webp/seat/jamsil_green.webp
  src/assets/webp/seat/jamsil_navy.webp
  src/assets/webp/seat/jamsil_orange.webp
  src/assets/webp/seat/jamsil_premium.webp
  src/assets/webp/seat/jamsil_red.webp
  src/assets/webp/seat/jamsil_table.webp
  src/assets/webp/seat/kt_alphashopping.webp
  src/assets/webp/seat/kt_central.webp
  src/assets/webp/seat/kt_cheer.webp
  src/assets/webp/seat/kt_default.webp
  src/assets/webp/seat/kt_exciting.webp
  src/assets/webp/seat/kt_genietv.webp
  src/assets/webp/seat/kt_geniezone.webp
  src/assets/webp/seat/kt_kidsland.webp
  src/assets/webp/seat/kt_outfield.webp
  src/assets/webp/seat/kt_sky.webp
  src/assets/webp/seat/kt_skyzone.webp
  src/assets/webp/seat/kt_tving.webp
  src/assets/webp/seat/kt_ybox.webp
  src/components/button/FloatingChatbotButton.tsx
  src/pages/Chatbot/components/ChatbotStart.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/components/JamsilSeat.tsx
  src/pages/Main/components/KtwizSeat.tsx
Labels: 🎨 design, 🐰 EUNHAK

#53 (#51) fix: 메인홈 웹 반응형 구현
  src/constants/ReactionData.ts
  src/pages/Main/components/JamsilSeat.tsx
  src/pages/Main/components/KtwizSeat.tsx
Labels: 🐞 fix, 🚀 feat, 🐻 INAE

#61 (#60) 🎨 design: 야구 직관 Tip 이미지 딜레이 현상 조정 외 세부 디자인 수정
  package-lock.json
  public/android-icon-144x144.png
  public/android-icon-192x192.png
  public/android-icon-36x36.png
  public/android-icon-48x48.png
  public/android-icon-72x72.png
  public/android-icon-96x96.png
  public/apple-icon-114x114.png
  public/apple-icon-120x120.png
  public/apple-icon-144x144.png
  public/apple-icon-152x152.png
  public/apple-icon-180x180.png
  public/apple-icon-57x57.png
  public/apple-icon-60x60.png
  public/apple-icon-72x72.png
  public/apple-icon-76x76.png
  public/apple-icon-precomposed.png
  public/apple-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-96x96.png
  public/favicon.ico
  public/manifest.json
  public/ms-icon-144x144.png
  public/ms-icon-150x150.png
  public/ms-icon-310x310.png
  public/ms-icon-70x70.png
  src/components/dialogs/BignnerGuideDialog.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/components/StadiumInfo.tsx
  src/pages/_app.tsx
Labels: 🎨 design, 🚀 feat, 🐻 INAE

#64 (#62) 🎨 design: 코치마크, Tip 버튼, 준비중인 서비스 페이지 작업
  src/assets/svg/guide_tip_button.svg
  src/assets/svg/recommend_tip_pink.svg
  src/assets/webp/bignnerGuide01.webp
  src/assets/webp/bignnerGuide02.webp
  src/assets/webp/bignnerGuide03.webp
  src/assets/webp/bignnerGuide04.webp
  src/assets/webp/coachmark01.webp
  src/assets/webp/coachmark02.webp
  src/assets/webp/coachmark03.webp
  src/assets/webp/recommend_tip_pink.webp
  src/assets/webp/service_ready.webp
  src/constants/tipData.ts
  src/pages/Culture/Culture.tsx
  src/pages/Guide/components/GuideDetailContent.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/Recommend/Result.tsx
Labels: 🎨 design, 🐰 EUNHAK

#66 (#63) 🎨 design: MS Clarity 설정 외 메인홈 스크롤 효과
  src/assets/webp/main_scroll.webp
  src/hooks/useRefScroll.ts
  src/hooks/useScroll.ts
  src/hooks/useVisibilityWithFade.ts
  src/pages/Main/Main.tsx
  src/pages/Main/components/ScrollAppeal.tsx
  src/pages/_app.tsx
Labels: 🎨 design, 🚀 feat, 🐻 INAE

#67 (#65) 🚀 feat: 추천 결과 카카오톡 공유하기 기능 구현
  .husky/_/pre-push
  package-lock.json
  package.json
  src/assets/svg/kakao_share.svg
  src/components/button/KakaoShareButton.tsx
  src/components/layout/ResultHeader.tsx
  src/pages/Recommend/Result.tsx
  src/pages/_app.tsx
  src/types/kakao.d.ts
  src/utils/kakaoMessage.ts
  tsconfig.json
Labels: 🎨 design, 🚀 feat, 🐰 EUNHAK

#69 (#68) 🎨 design: 수정된 디자인 적용 및 구장별 구역가이드 헤더 변경 기능
  src/assets/svg/baseballTip.svg
  src/assets/svg/recommend_tip_pink.svg
  src/components/dialogs/BignnerGuideDialog.tsx
  src/components/layout/BackBar.tsx
  src/components/layout/BackGuideHeader.tsx
  src/components/layout/ResultHeader.tsx
  src/components/page/ServiceReady.tsx
  src/pages/Culture/Culture.tsx
  src/pages/Guide/Guide.tsx
  src/pages/Guide/components/GuideDetailContent.tsx
  src/pages/Main/Main.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/Recommend/Result.tsx
Labels: 🎨 design, 🐰 EUNHAK

#71 (#47) 🎨 design: 챗봇 가이드 구현
  src/api/ChatbotApiHandler.ts
  src/assets/svg/chatbot_category_open_button_gray.svg
  src/assets/svg/chatbot_floating_button.svg
  src/assets/svg/chatbot_lookie.svg
  src/assets/svg/chatbot_profile.svg
  src/assets/webp/chatbot_floating_button.webp
  src/assets/webp/chatbot_manual.webp
  src/assets/webp/chatbot_message_left_tail_white_big.webp
  src/assets/webp/chatbot_message_left_tail_white_small..webp
  src/assets/webp/chatbot_message_right_tail_pink_big.webp
  src/assets/webp/chatbot_message_right_tail_pink_small.webp
  src/assets/webp/chatbot_profile.webp
  src/assets/webp/chatbot_prohibition.webp
  src/components/button/FloatingChatbotButton.tsx
  src/components/layout/BackBar.tsx
  src/components/layout/BackLogoBar.tsx
  src/components/layout/HeaderBackBar.tsx
  src/components/layout/HeaderBar.tsx
  src/components/layout/HeaderCenter.tsx
  src/components/layout/MainHeader.tsx
  src/constants/ChatbotData.ts
  src/hooks/TestCustomHook.ts
  src/hooks/useDate.ts
  src/pages/Chatbot/Chatbot.tsx
  src/pages/Chatbot/components/CategoryChat.tsx
  src/pages/Chatbot/components/ChatInput.tsx
  src/pages/Chatbot/components/ChatbotInputField.tsx
  src/pages/Chatbot/components/ChatbotStart.tsx
  src/pages/Chatbot/components/DateBanner.tsx
  src/pages/Chatbot/components/OptionsList.tsx
  src/pages/Chatbot/components/RookieChat.tsx
  src/pages/Chatbot/components/StadiumSelection.tsx
  src/pages/Chatbot/components/UserChat.tsx
  src/pages/Chatbot/components/category/FAQCategoryBar.tsx
  src/pages/Chatbot/components/category/FAQCategoryButton.tsx
  src/pages/Chatbot/components/message/RookieMessage.tsx
  src/pages/Chatbot/components/message/RookieMessageWithTail.tsx
  src/pages/Chatbot/components/message/UserMessageWithTail.tsx
  src/pages/Chatbot/components/rookie/RookieProfile.tsx
  src/pages/Chatbot/components/stadiumcategory/StadiumSelection.tsx
  src/pages/Chatbot/components/test/ChabotDataTestPage.tsx
  src/pages/Main/components/SeatRecommendButton.tsx
  tailwind.config.ts
Labels: 🎨 design, 🐻 INAE

#78 (#72) 🚀 feat: 챗봇 가이드 세부 디테일 수정 및 API 데이터 추가
  package-lock.json
  src/api/ChatbotApiHandler.ts
  src/api/ChatbotApiType.ts
  src/components/dialogs/ImageModal.tsx
  src/components/dialogs/ImgUrlModal.tsx
  src/constants/ChatbotData.ts
  src/constants/ZoneData.ts
  src/hooks/useImageModal.ts
  src/pages/Chatbot/Chatbot.tsx
  src/pages/Chatbot/components/CategoryChat.tsx
  src/pages/Chatbot/components/DateBanner.tsx
  src/pages/Chatbot/components/RookieChat.tsx
  src/pages/Chatbot/components/UserChat.tsx
  src/pages/Chatbot/components/input/ChatbotInputField.tsx
  src/pages/Chatbot/components/input/FAQCategoryBar.tsx
  src/pages/Chatbot/components/input/FAQCategoryButton.tsx
  src/pages/Chatbot/components/message/RookieMessage.tsx
  src/pages/Chatbot/components/message/RookieMessageWithTail.tsx
  src/pages/Chatbot/components/message/UserMessageWithTail.tsx
  src/pages/Chatbot/components/message/custom/RookieImageMessage.tsx
  src/pages/Chatbot/components/message/custom/RookieImgUrlMessage.tsx
  src/pages/Chatbot/components/message/custom/RookiePreformattedButtonMessage.tsx
  src/pages/Chatbot/components/message/custom/RookiePreformattedButtonMessageWithTail.tsx
  src/pages/Chatbot/components/message/custom/RookiePreformattedMessage.tsx
  src/pages/Chatbot/components/message/custom/RookiePreformattedMessageWithTail.tsx
  src/pages/Chatbot/components/message/custom/RookieWhiteListMessage.tsx
  src/pages/Chatbot/components/message/custom/RookieWhiteListMessageWithTail.tsx
Labels: 🎨 design, 🚀 feat, 🐻 INAE, 🔄 refactor

#81 (#73) 🎨 design: 온보딩 플로우 구현
  src/assets/webp/onboarding_welcome_rookie.webp
  src/assets/webp/onboarding_welcome_zone_background.webp
  src/components/dialogs/ImageModal.tsx
  src/pages/Chatbot/components/message/custom/RookieImageMessage.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Main/Main.tsx
  src/pages/Onboarding/Login/InitPage.tsx
  src/pages/Onboarding/Signup/SignupPage3.tsx
  src/pages/_app.tsx
Labels: 🎨 design, 🚀 feat, 🐻 INAE

#85 (#82) 🎨 design: 렌더링 관련 디테일 디자인 수정
  package-lock.json
  src/components/dialogs/ImgUrlModal.tsx
  src/context/StadiumContext.tsx
  src/hooks/useGlobalScroll.ts
  src/hooks/useRefScroll.ts
  src/hooks/useStadiumSelector.ts
  src/pages/Guide/Guide.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Main/Main.tsx
  src/pages/Onboarding/Signup/SignupPage3.tsx
  src/pages/_app.tsx
Labels: 🎨 design, 🚀 feat, 🐻 INAE

#86 (#84) 🎨 design: 야구문화 페이지
  src/assets/svg/next_button_gray.svg
  src/components/dropdown/BigDropdown.tsx
  src/components/layout/CultureHeader.tsx
  src/constants/CultureData.ts
  src/pages/Culture/Culture.tsx
  src/pages/Culture/Entertainment/Entertainment.tsx
  src/pages/Culture/Entertainment/components/EntertainmentModal.tsx
  src/pages/Culture/Entertainment/components/EntertainmentPhotoCard.tsx
  src/pages/Culture/Entertainment/components/EntertainmentViewAllPage.tsx
  src/pages/Culture/Food/Food.tsx
  src/pages/Culture/Food/components/FoodModal.tsx
  src/pages/Culture/Food/components/FoodPhotoCard.tsx
  src/pages/Culture/Food/components/FoodViewAllPage.tsx
  src/pages/Culture/components/AllPageHeader.tsx
  src/pages/Culture/components/TabBackgroundPink.tsx
  src/pages/Culture/components/TabTextPink.tsx
  src/pages/Culture/components/ViewAllButton.tsx
Labels: 🎨 design, 🐰 EUNHAK
